// Temporary placeholder generated by setup. Replace with FlutterFire CLI output.
// Run: flutter pub global activate flutterfire_cli
// Then: flutterfire configure --project <your-firebase-project-id>

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnhkwrU75YFmgiIuNF1Yt2rL7685-4y8',
    appId: '1:528112879706:web:65fe0a1e756f15ef67f063',
    messagingSenderId: '528112879706',
    projectId: 'facebook-clone-fcd8e',
    authDomain: 'facebook-clone-fcd8e.firebaseapp.com',
    storageBucket: 'facebook-clone-fcd8e.firebasestorage.app',
  );

  // DUMMY VALUES – replace via FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nhCs6Vet1Cnahf4NyK2PQB84SJoH2Rw',
    appId: '1:528112879706:android:85802dd2b2d8e04c67f063',
    messagingSenderId: '528112879706',
    projectId: 'facebook-clone-fcd8e',
    storageBucket: 'facebook-clone-fcd8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMi5GRkzXySQYEx6DbyGYvnrPKsTV1qM',
    appId: '1:528112879706:ios:c1888966255521f567f063',
    messagingSenderId: '528112879706',
    projectId: 'facebook-clone-fcd8e',
    storageBucket: 'facebook-clone-fcd8e.firebasestorage.app',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMi5GRkzXySQYEx6DbyGYvnrPKsTV1qM',
    appId: '1:528112879706:ios:c1888966255521f567f063',
    messagingSenderId: '528112879706',
    projectId: 'facebook-clone-fcd8e',
    storageBucket: 'facebook-clone-fcd8e.firebasestorage.app',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnnhkwrU75YFmgiIuNF1Yt2rL7685-4y8',
    appId: '1:528112879706:web:84dd5c77c0305e5b67f063',
    messagingSenderId: '528112879706',
    projectId: 'facebook-clone-fcd8e',
    authDomain: 'facebook-clone-fcd8e.firebaseapp.com',
    storageBucket: 'facebook-clone-fcd8e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_WITH_API_KEY',
    appId: 'REPLACE_WITH_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
  );
}